name: Docker Image CI

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:
  build_and_push_to_docker_hub:
    name: Push Docker image to Docker Hub
    runs-on: ubuntu-latest
    env:
      IMAGE_TAG: ${{ github.run_number }}

    steps:
    - name: Print Current Working Directory
      run: pwd

    - name: Extract metadata (tags, labels) for Docker
      id: meta
      uses: docker/metadata-action@v3
      with:
        images: himanshuwappnet/private

    - name: Set timestamp environment variable
      id: set_tag
      run: echo "IMAGE_TAG=$(date +%s)" >> $GITHUB_ENV
